api_version = "2024-07"

[[extensions]]
type = "function"
name = "Price Threshold Discount"
handle = "price-threshold-discount"

[extensions.build]
command = "npm run build"
path = "dist/index.wasm"
watch = ["src/**/*.js"]

[[extensions.targeting]]
target = "purchase.product-discount.run"
module = "./src/run.js"
export = "run"
input_query = "./src/run.graphql"
